

<form action="" method="post">
    <p>Пример: Huawei Technologies</p>
    <label for="switch_manufacturer">Производитель свича</label>
    <input name="switch_manufacturer" id ="switch_manufacturer" type="text" required />
    <label for="model_name">Модель свича</label>
    <input name="model_name" id ="model_name" type="text" required />
    <label for="firmware">Версия пошивки свича</label>
    <input name="firmware" id ="firmware" type="text" required />
    <input type="submit"/>
</form>