<h2> История пользователя <?= $account_id ?></h2>
<div>
    <?php foreach (Session::getFlash($account_id) as $v): ?>

        <p class="<?= $v['warning_class']; ?>"><?= $v['warning_level']; ?>: <?= $v['message']; ?></p>
    <?php endforeach; ?>
</div>

<table border="1">
    <tr>
        <td>Дата-время</td>
        <td>Свич ip</td>
        <td>Макадрес</td>
        <td>Порт</td>
        <td>Модель свича</td>
        <td>Прошивка свича</td>
        <td>Состояние порта</td>
        <td>счетчик(in), байт</td>
        <td>счетчик(out), байт</td>
        <td>счетчик пакетов</td>
        <td>Ошибки</td>
        <td>Скорость</td>
        <td>Время последнего изменения порта</td>
    </tr>
    <?php foreach($data_history as $v ): ?>


    <tr>
        <td><?= $v['date_time'] ?></td>
        <td><?= $v['switch_ip'] ?></td>
        <td><?= $v['mac'] ?></td>
        <td><?= $v['port'] ?></td>
        <td><?= $v['switch_model'] ?></td>
        <td><?= $v['firmware'] ?></td>
        <td><?= $v['port_status'] ?></td>
        <td><?= $v['counter_byte_in'] ?></td>
        <td><?= $v['counter_byte_out'] ?></td>
        <td><?= $v['counter_pkts_out'] ?></td>
        <td><?= $v['error'] ?></td>
        <td><?= $v['speed'] ?></td>
        <td><?= $v['last_change'] ?></td>
    </tr>
    <?php endforeach; ?>

</table>