<h1> Пользователь <?= $account_id ?></h1>
<div>



        <?php foreach(Session::getFlash() as $v): ?>

            <p> <?= $v; ?></p>
        <?php endforeach; ?>



</div>

<table border="1">
    <tr>
        <td colspan="2">Данные полученные со свича</td>
    </tr>
    <tr>
        <td>Состояние порта</td>
        <td><?= isset($data_switch['port_status']) ? $data_switch['port_status'] : 'Нет данных' ?></td>
    </tr>
    <tr>
        <td>счетчик(in), байт</td>
        <td><?= isset($data_switch['counter_byte_in']) ? $data_switch['counter_byte_in'] : 'Нет данных' ?></td>
    </tr>

    <tr>
        <td>счетчик(out), байт</td>
        <td><?= isset($data_switch['counter_byte_out']) ? $data_switch['counter_byte_out'] : 'Нет данных' ?></td>
    </tr>
    <tr>
        <td>счетчик пакетов</td>
        <td><?= isset($data_switch['counter_pkts_out']) ? $data_switch['counter_pkts_out'] : 'Нет данных' ?></td>
    </tr>
    <tr>
        <td>Ошибки</td>
        <td><?= isset($data_switch['error']) ? $data_switch['error'] : 'Нет данных' ?></td>
    </tr>
    <tr>
        <td>Скорость мб/с</td>
        <td><?= isset($data_switch['speed']) ? $data_switch['speed'] : 'Нет данных' ?></td>
    </tr>
    <tr>
        <td>Состояние кабеля</td>
        <td><?= (isset($data_switch['cable_status']) && Config::get('cabletest_on_off')== 'on') ? $data_switch['cable_status'] : 'Нет данных' ?></td>
    </tr>
    <tr>
        <td>Длина кабеля</td>
        <td><?= (isset($data_switch['cable_lenght']) && Config::get('cabletest_on_off')== 'on') ? $data_switch['cable_lenght'] : 'Нет данных' ?></td>
    </tr>
    <tr>
        <td>Время последнего изменения порта</td>
        <td><?= isset($data_switch['last_change']) ? $data_switch['last_change'] : 'Нет данных' ?></td>
    </tr>
    <?php
    if (isset($data_switch['last_change'])):
        foreach ($data_switch['mac'] as $k => $v): ?>

            <tr>
                <td>Мак адрес № <?= $k + 1; ?></td>
                <td><?= $v; ?></td>
            </tr>

        <?php endforeach;
    else:?>

        <tr>
            <td>Мак адрес</td>
            <td>Нет данных</td>
        </tr>

        <?php endif; ?>

    <tr>
        <td colspan="2">Данные полученные из базы данных билинга</td>
    </tr>
    <tr>
        <td>ip свича</td>
        <td><?= $data_db['switch_ip'] ? $data_db['switch_ip'] : 'Нет данных' ?></td>
    </tr>
    <tr>
        <td>Мак адрес пользователя</td>
        <td><?= $data_db['mac'] ? $data_db['mac'] : 'Нет данных' ?></td>
    </tr>
    <tr>
        <td>Порт</td>
        <td><?= $data_db['port'] ? $data_db['port'] : 'Нет данных' ?></td>
    </tr>
    <tr>
        <td>Модель свича</td>
        <td><?= $data_db['switch_model'] ? $data_db['switch_model'] : 'Нет данных' ?></td>
    </tr>
    <tr>
        <td>Прошивка свича</td>
        <td><?= $data_db['firmware'] ? $data_db['firmware'] : 'Нет данных' ?></td>
    </tr>
    <tr>
        <td>Время отработки свича, с</td>
        <td><?=  microtime(true)-$GLOBALS['start_time']; ?></td>
    </tr>
</table>

<div><a href="/account_test/history/<?= $account_id ?>" target="_blank">История пользователя</a></div>

