<!DOCTYPE html>
<!--[if lt IE 7]>
<html lang="ru" class="lt-ie9 lt-ie8 lt-ie7"><![endif]-->
<!--[if IE 7]>
<html lang="ru" class="lt-ie9 lt-ie8"><![endif]-->
<!--[if IE 8]>
<html lang="ru" class="lt-ie9"><![endif]-->
<!--[if gt IE 8]><!-->
<html lang="ru">
<!--<![endif]-->
<head>

    <meta charset="UTF-8"/>
    <title>test</title>
    <meta name="description" content=""/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>


  <!--  <link rel="stylesheet" href="/Applicationroot/css/css_reset.css"/> -->
    <link rel="stylesheet" href="/Applicationroot/css/fonts.css"/>
    <link rel="stylesheet" href="/Applicationroot/css/main.css"/>

</head>
<body>
<nav>
    <ul>
        <li><a href="/account_test">Главная</a></li>
        <li><a href="#">Биллинг</a></li>
        <li><a href="account_test/admin">Админ панель</a></li>
    </ul>
</nav>

<?= $content ?>



</body>
</html>